[CMOB-1993]basic_design
ninikokra/MovieApp pull request #1
Opened 2023-07-20 12:17 UTC by ninikokra

https://spaceneobank.atlassian.net/browse/CMOB-1993

2023-07-21 10:14 UTC, etozheluka requested changes

2023-07-21 10:14 UTC, etozheluka commented on app/src/main/java/com/space/movieapp/presentation/views/CustomBottomNavigation.kt
> +    }
with(binding)

2023-07-21 10:14 UTC, etozheluka commented on app/src/main/java/com/space/movieapp/presentation/views/CustomBottomNavigation.kt
> +    }
ContextCompat.getColor extension დაწერე

2023-07-21 10:14 UTC, etozheluka commented on app/src/main/java/com/space/movieapp/presentation/views/CustomSearchBar.kt
> +    }
binding.searchBarEditText.addTextChangedListener ეს რომ გამოიყენო ?

2023-07-21 10:14 UTC, etozheluka commented on app/src/main/java/com/space/movieapp/presentation/views/CustomSearchBar.kt
> +
extra line

2023-07-21 10:14 UTC, etozheluka commented on app/src/main/java/com/space/movieapp/presentation/views/CustomSearchBar.kt
> +                    context,
color-ის extension

2023-07-21 10:14 UTC, etozheluka commented on app/src/main/res/layout/activity_movies.xml
> +        app:layout_constraintTop_toTopOf="parent"
constaint არ უნდა როცა match_parent გიწერია

2023-07-21 10:14 UTC, etozheluka commented on app/src/main/res/values/colors.xml
> +
lines

2023-07-21 10:14 UTC, etozheluka commented on app/src/main/res/values/strings.xml
> +    <string name="hello_blank_fragment">Hello blank fragment</string>
ამას ალბათ არ იყენებ

2023-07-31 08:06 UTC, gioqemoklidze requested changes

2023-07-31 08:06 UTC, gioqemoklidze commented on app/src/main/res/layout/fragment_details.xml
> +        android:text="Thirteen-year-old fledgling writer Briony Tallis irrevocably changes the course of several lives when she accuses her older sister's lover of a crime he did not commit."
dont forget to delete this texts

2023-07-31 11:14 UTC, ninikokra commented on app/src/main/res/layout/fragment_favorites.xml
> +        android:visibility="visible"
i was testing visibilities and forgot to delete it :D thx. removed!

2023-08-09 09:16 UTC, merged